### ISSUE TITLE
Budgets: additional funding sources task list status and diff issue[5]

### ISSUE THREAD

**Issue by Sepehr-Sobhani** [bcgov/cas-cif#1036]
Describe the Bug:

Adding a new additional funding source to a funding agreement that already has 1 or more additional funding sources triggers no change in the task list (even with validation errors) and does not show up in the diff.

Note: additional funding source fields are required only by the schema and not by the database

Probability (how likely the bug is to happen, scored from 1-5): 3
(For example, probability of 5 is something like "it happens to all users every time they log in."
Probability of 1 "only happens to certain users when a really specific and unlikely path is followed.")

Effect (how bad the bug is when it does happen, scored from 1-5): 2
(For example, effect of 5 is "the entire app crashes and makes it unusable for all users" or "the bug causes the wrong data to be saved, with critical information (e.g. payment) being affected."
Effect of 1 is "It makes some styling look a little bit weird.")

Steps to reproduce the behaviour:

take an existing project that has an additional funding source -> add a new additional funding source (task list status is still the same) -> submit -> go to summary page ->  diff is not showing up for the added additional funding source

Screenshots:
https://www.loom.com/share/e9eb8816658445c7ac97ea3235c6425d

Resolution:
- Show an "Updated" message on the diff view, and the new values - with no information about the diff itself

Additional information:

- Browser: [e.g. chrome, safari]
- Version: [e.g. 22]
- Additional context

**Comment by dleard** [comment]
This is related to #1360. If we do #1360 this work is not needed (or more accurately, will still be needed but handled differently in #1360), since we will change how additional funding sources are included in the funding agreement form. If we are not going to do #1360 for some time, then we should fix this bug, but if we plan to do #1360 in the near future then this will be duplicated / thrown out work.

**Comment by BCerki** [comment]
Starting on 1360

**Comment by pbastia** [comment]
Make sure this bug is still happening after #1360 was completed

**Comment by Sepehr-Sobhani** [comment]
I've tested this on #1360 and it's not happening anymore.

**Comment by pbastia** [comment]
Slick! Thank you @Sepehr-Sobhani. Closing.
